spring.application.name=PortfolioBackend
server.port=4000

# Disable database and Redis autoconfigurations as data is JSON-file backed
spring.autoconfigure.exclude=org.springframework.boot.autoconfigure.jdbc.DataSourceAutoConfiguration,\
  org.springframework.boot.autoconfigure.orm.jpa.HibernateJpaAutoConfiguration,\
  org.springframework.boot.autoconfigure.data.redis.RedisAutoConfiguration

spring.session.store-type=none
spring.docker.compose.enabled=false

