services:
  portfolio-backend:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: portfolio-backend
    restart: unless-stopped
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - BYOSHELL_API_URL=${BYOSHELL_API_URL:-https://codecrafters-shell-rust.onrender.com}
      - BYOSHELL_API_KEY=${BYOSHELL_API_KEY}
